#! /bin/bash

source ../.env
SERVER_CSR_CONF='appcsr.conf'

#Generate CA key 
if test -f "$CA_KEY"; then
    echo "$CA_KEY exists. skipping the generation"
else 
    echo "############ Generate CA key ####################"
    openssl genrsa -des3 -out $CA_KEY -passout pass:$CA_ROOT_PWD 2048
fi

#Generate ca cert
if test -f "$CA_ROOT"; then
    echo "$CA_ROOT exists. skipping the generation"
else 
    echo "############ Generate CA Cert ####################"
    openssl req -x509 -new -nodes -key $CA_KEY -sha256 -days 1825 \
    -passin pass:$CA_ROOT_PWD \
    -subj "/C=SN/ST=Singapore/L=Singapore/O=Hey Prod Technologies/OU=ninja/CN=heyprod.com" \
    -out $CA_ROOT
fi



#Generate server key
if test -f "$SERVER_KEY"; then
    echo "$SERVER_KEY exists. skipping the generation"
else 
    echo "############ Generate Server key ####################"
    openssl genrsa -des3 -out $SERVER_KEY -passout pass:$SERVER_CRT_KEY_PWD 2048
fi

#Generate CSR
if test -f "$SERVER_CSR"; then
    echo "$SERVER_CSR exists. skipping the generation"
else 
    echo "############ Generate Server CSR ####################"
    openssl req -new -key $SERVER_KEY -out $SERVER_CSR -passin pass:$SERVER_CRT_KEY_PWD -config $SERVER_CSR_CONF 
fi

#Generate application certs
if test -f "$SERVER_CRT"; then
    echo "$SERVER_CRT exists. skipping the generation"
else 
    echo "############ Generate Server Certs ####################"
    openssl x509 -req \
        -in $SERVER_CSR \
        -CA $CA_ROOT -CAkey $CA_KEY \
        -CAcreateserial -out $SERVER_CRT \
        -passin pass:$CA_ROOT_PWD \
        -days 365 \
        -sha256 -extensions req_ext -extfile $SERVER_CSR_CONF
fi

#Generate server p12
if test -f "$SERVER_P12"; then
    echo "$SERVER_P12 exists. skipping the generation"
else 
    echo "############ Generate Server p12 ####################"
    openssl pkcs12 -export -in $SERVER_CRT \
        -inkey $SERVER_KEY \
        -out $SERVER_P12 -name server \
        -passin pass:$SERVER_CRT_KEY_PWD \
        -passout pass:$SERVER_P12_PWD \
        -CAfile $CA_ROOT -caname heyprod.com
fi

cp $SERVER_P12 ../keycloak/$SERVER_P12
cp $CA_ROOT ../keycloak/$CA_ROOT

cp $SERVER_CRT ../kong/$SERVER_CRT
openssl rsa -in $SERVER_KEY -passin pass:$SERVER_CRT_KEY_PWD -out ../kong/$SERVER_KEY 

# rm -rf app.* root.* kong.key


