version: '3.8'
services:
  postgres:
    container_name: postgres 
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PWD}
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-config:
    container_name: postgres-config
    depends_on:
      postgres:
        condition: service_healthy

    build: postgres-config
    environment:
      TF_VAR_db_admin_password: ${POSTGRES_ADMIN_PWD}
      TF_VAR_db_admin_user: ${POSTGRES_ADMIN_USER}
      TF_VAR_db_keycloak_password: ${POSTGRES_USER_KEYCLOAK_PWD}
    volumes:
      - pstfstate:/state
    
  otel:
    container_name: otel
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel/config.yaml:/etc/otel-config.yaml
      - ./certs/${CA_ROOT}:/etc/root.crt
    command:
      '--config=/etc/otel-config.yaml'
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    container_name: jaeger 
    image: jaegertracing/all-in-one:1.17.1
    ports: 
      - '6831:6831/udp'
      - '5778:5778'
      - '14268:14268'
      - '16686:16686'
  keycloak:
    container_name: keycloak 
    depends_on:
      postgres:
        condition: service_healthy
      postgres-config:
        condition: service_started
      otel:
        condition: service_started
    build: 
      context: keycloak
      args:
        SERVER_P12: ${SERVER_P12}
        SERVER_P12_PWD: ${SERVER_P12_PWD}
        CA_ROOT: ${CA_ROOT}
    restart: always
    command: ["start","--optimized"]
    environment:
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_USER_KEYCLOAK_PWD}
      KC_HOSTNAME: keycloak
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_NAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PWD}
      JAVA_OPTS_APPEND: "-javaagent:/tmp/opentelemetry-javaagent.jar -Dotel.javaagent.exclude-classes=org.keycloak.services.resources.RealmsResource"
      OTEL_SERVICE_NAME: keycloak
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      # QUARKUS_HTTP_ACCESS_LOG_ENABLED: "true" # Only For debugging
      # QUARKUS_HTTP_ACCESS_LOG_PATTERN: '%r\n%{ALL_REQUEST_HEADERS}' # Only For debugging
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4317
    ports:
      - '8443:8443'
    healthcheck:
      test: ["CMD-SHELL", "curl -k --fail https://localhost:8443/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak-config: 
    container_name: keycloak-config
    depends_on:
      keycloak:
        condition: service_healthy

    build: keycloak-config
    environment:
      TF_VAR_kc_host: keycloak
      TF_VAR_kc_port: 8443
      TF_VAR_kc_admin_username: ${KEYCLOAK_ADMIN_NAME}
      TF_VAR_kc_admin_password: ${KEYCLOAK_ADMIN_PWD}
      TF_VAR_kc_realm_name: ${KEYCLOAK_REALM_NAME}
      TF_VAR_kc_client_id: ${KEYCLOAK_CLIENT_ID}
      TF_VAR_kc_client_pwd: ${KEYCLOAK_CLIENT_PWD}
      TF_VAR_kc_client_root_url: https://kong

    volumes:
      - kctfstate:/state
  kong:
    container_name: kong 
    image: kong:3.0.0-alpine-docker
    build:
      context: kong
      args:
        SERVER_CRT: ${SERVER_CRT}
        SERVER_KEY: ${SERVER_KEY}
        KC_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        KC_CLIENT_PWD: ${KEYCLOAK_CLIENT_PWD}
        KC_HOST: keycloak
        KC_PORT: 8443
        KC_REALM: ${KEYCLOAK_REALM_NAME}
    depends_on:
      keycloak:
        condition: service_healthy
      otel:
        condition: service_started
    environment:
      KONG_DATABASE: "off" 
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8444 ssl
      KONG_DECLARATIVE_CONFIG: /kong.yaml
      KONG_PLUGINS: rate-limiting,opentelemetry,oidc
      KONG_SSL: "on"
      KONG_SSL_CERT: /certs/${SERVER_CRT}
      KONG_SSL_CERT_KEY: /certs/${SERVER_KEY}
      KONG_LUA_PACKAGE_PATH: /usr/local/kong-oidc/?.lua;
      KONG_LOG_LEVEL: warn
      KONG_OPENTELEMETRY_TRACING: all
    ports: 
      - 443:8443
      - 8444:8444
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/dashboards:/provisioning/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./certs/${SERVER_CRT}:/var/lib/grafana/ssl/${SERVER_CRT}
      - ./certs/${SERVER_KEY_DEC}:/var/lib/grafana/ssl/${SERVER_KEY_DEC}
    ports:
      - 3000:3000
    environment:
      LOGSPOUT: ignore
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_HOME_PAGE: /d/Xbo7ftQnz/keycloak?orgId=1
      GF_SERVER_CERT_FILE: /var/lib/grafana/ssl/${SERVER_CRT}
      GF_SERVER_CERT_KEY: /var/lib/grafana/ssl/${SERVER_KEY_DEC}
      GF_SERVER_PROTOCOL: https
    depends_on:
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command: 
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
volumes:
  postgres:
    driver: local
  pstfstate:
    driver: local
  kctfstate:
    driver: local
  