apiVersion: 1
datasources:
  - name: jaeger
    uid: jaegerpoc
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: "60s"
      httpMethod: "POST"

