{
 "title": "Keycloak",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Please wait a minute if you don't see any values."
   }
  },
  {
   "title": "Keycloak traces [Jaeger]",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
   "targets": [
    { "service": "keycloak" }
   ]
  },
  {
   "title": "Keycloak metrics - CPU utilization [Prometheus]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{instance=\"keycloak:8443\"}"
    }
   ]
  },
  {
   "title": "Keycloak metrics - used heap size [Prometheus]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{instance=\"keycloak:8443\"}"
    }
   ]
  },
  {
   "title": "Keycloak logs [Elasticsearch]",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Keycloak logs [Elasticsearch]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Keycloak SLI metric - avg latency [Prometheus]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg by(sli) (slimetric_avg_latency{app=\"keycloak\"})",
     "legendFormat": "{{sli}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}