#! /bin/bash
PASS="${1:='HeyProd1234'}"
CA_KEY='hey-prod-ca.key'
CA_ROOT='hey-prod-root.pem'

#Generate CA key 
openssl genrsa -des3 -out $CA_KEY -passout pass:$PASS 2048

#Generate root cert
openssl req -x509 -new -nodes -key $CA_KEY -sha256 -days 1825 \
-passin pass:$PASS \
-subj "/C=SN/ST=Singapore/L=Singapore/O=Hey Prod Technologies/OU=ninja/CN=heyprod.com" \
-out $CA_ROOT
