
FROM kong:2.8.1-alpine

ENV OIDC_PLUGIN_VERSION=1.2.3-2
ENV JWT_PLUGIN_VERSION=1.1.0-1
ENV GIT_VERSION=2.24.4-r0
ENV UNZIP_VERSION=6.0-r7
ENV LUAROCKS_VERSION=2.4.4-r1


USER root
RUN apk update && apk add git unzip luarocks
RUN luarocks install kong-oidc
RUN luarocks install kong-plugin-jwt-keycloak
# WORKDIR /
# RUN git clone --branch 20200505-access-token-processing https://github.com/BGaunitz/kong-plugin-jwt-keycloak.git
# WORKDIR /kong-plugin-jwt-keycloak
# RUN luarocks make

# RUN luarocks pack kong-plugin-jwt-keycloak ${JWT_PLUGIN_VERSION} \
#      && luarocks install kong-plugin-jwt-keycloak-${JWT_PLUGIN_VERSION}.all.rock

COPY ./kong.yaml /kong.yaml
COPY ./server.crt /certs/
COPY ./server.key /certs/

USER kong